// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/generate-image-manifest.mjs

export const AVAILABLE_SHOE_IMAGES = new Set<string>([
  '/shoes/gel-kayano-32.webp',
  '/shoes/gel-nimbus-28.webp',
  '/shoes/glideride-max-2.webp',
  '/shoes/magic-speed-5.webp',
  '/shoes/megablast.webp',
  '/shoes/metaspeed-edge-tokyo.webp',
  '/shoes/metaspeed-ray.webp',
  '/shoes/metaspeed-sky-tokyo.webp',
  '/shoes/novablast-5.webp',
  '/shoes/placeholder-shoe.svg',
  '/shoes/sonicblast.webp',
  '/shoes/superblast-2.webp',
  '/shoes/yogiri-s4-plus.webp',
]);

export function hasShoeImage(imagePath: string): boolean {
  return AVAILABLE_SHOE_IMAGES.has(imagePath);
}
